### ISSUE TITLE
Methods orders (Fig 1A)

### ISSUE THREAD

**Issue by gongx030** [erikjskie/ensemblemerge_project#1]
@erikjskie 

Please make the methods in Fig 1A the same order as in Fig 1B and Supplementary Fig 3, that is, the order should be:

* EnsembleMerge
* Seruat
* Harmony
* Scanorma
* Liger
* Scanorama
* BBKNN
* Uncorrected

**Comment by erikjskie** [comment]
@gongx030 

Apologies, this has been updated in the figures and github

**Comment by gongx030** [comment]
Thanks. @erikjskie
