### ISSUE TITLE
Figure 1A legend and metrics order

### ISSUE THREAD

**Issue by gongx030** [erikjskie/ensemblemerge_project#2]
@erikjskie 

Please add the legends for Figure 1A.  The order of the metrics should be consistent with ones in Supplementary Figure 3:

**Comment by erikjskie** [comment]
@gongx030 

The legend has been added and metrics are reordered to be the same as supp. figure 3. (note: ARI cell is not present in supp. fig. 3, it is fig1b)

**Comment by gongx030** [comment]
@erikjskie Nice.
