### ISSUE TITLE
ARI Batch and ASW Batch

### ISSUE THREAD

**Issue by gongx030** [erikjskie/ensemblemerge_project#7]
@erikjskie 

When you calculated these two metrics, did you use (1 - ARI), instead of ARI itself?

**Comment by erikjskie** [comment]
@gongx030 

1-ARI and ASW for the batch

**Comment by gongx030** [comment]
@erikjskie 

Did you scale ASW to [0, 1] like what they did [here](https://openproblems.bio/neurips_docs/about_tasks/task3_joint_embedding/#bio-conservation-metrics)?

**Comment by erikjskie** [comment]
@gongx030 

Yes
